sudo: true
language: java
install: true
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      jdk: oraclejdk8
#    - os: osx
#      jdk: oraclejdk8




sudo: required

before_install:
  - ./start-broker.sh

script:
  - mvn -B clean -q
  - mvn -B --projects org.eclipse.paho.client.mqttv3,org.eclipse.paho.client.mqttv3.test test -q

#addons:
#  apt:
#    sources:
#      - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
#    packages:
#      - mosquitto
